// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.15/esri/copyright.txt for details.
//>>built
define("require exports @dojo/framework/shim/AbortController dojo/Deferred dojo/promise/all ./clock ./Error ./events ./has ./maybe ./Logger @dojo/framework/shim/Promise".split(" "),function(L,c,G,u,H,I,A,B,r,k,J){function C(a){return r("esri-native-promise")?Promise.all(a):H(a)}function h(a,b){if(r("esri-native-promise"))return new Promise(function(b,d){try{a(b,d)}catch(f){Promise.resolve().then(function(){return d(f)})}});var d=new u(b);try{a(function(a){return t(a).then(d.resolve)},d.reject)}catch(e){d.reject(e)}return d.promise}
function p(a){void 0===a&&(a="Aborted");a=new A("AbortError",a);a.dojoType="cancel";return a}function v(){return new G.default}function D(a){if(E(a))throw p();}function w(a){return k.isSome(a)?"aborted"in a?a:a.signal:a}function E(a){a=w(a);return k.isSome(a)&&a.aborted}function x(a,b){a=w(a);if(!k.isNone(a))if(a.aborted)b();else return B.once(a,"abort",function(){return b()})}function q(a){return a&&("AbortError"===a.name||"cancel"===a.dojoType)}function y(a){var b=null;a=h(function(a,e){b={resolve:a,
reject:e}},a);b.promise=a;b.cancel=function(){b.reject(p())};return b}function z(a){if(a){if("function"!==typeof a.forEach){var b=Object.keys(a),d=b.map(function(b){return a[b]});return z(d).then(function(a){var d={};b.forEach(function(b,e){return d[b]=a[e]});return d})}var e=null,c=l;return h(function(b,d){var f=[],n=a.length;0===n&&b(f);a.forEach(function(a){var g={promise:a||c(a)};f.push(g);g.promise.then(function(a){g.value=a}).catch(function(a){g.error=a}).then(function(){--n;0===n&&(e?d(p()):
b(f))})})},function(b){e=b||"Invocation cancellation";a.forEach(function(a){"cancel"in a&&a.cancel(b)})})}}function l(a){void 0===a&&(a=void 0);if(r("esri-native-promise"))return Promise.resolve(a);var b=new u;b.resolve(a);return b.promise}function F(a,b,d){void 0===b&&(b=void 0);var e=v();x(d,function(){return e.abort()});return h(function(d,c){var f=setTimeout(function(){f=0;d(b)},a);x(e,function(){f&&(clearTimeout(f),c(p()))})},function(){return e.abort()})}function t(a){return a&&"object"===typeof a&&
"then"in a&&"function"===typeof a.then?a:l(a)}Object.defineProperty(c,"__esModule",{value:!0});var K=J.getLogger("esri");c.all=C;c.filter=function(a,b){var d=a.slice();return C(a.map(function(a,d){return b(a,d)})).then(function(a){return d.filter(function(b,d){return a[d]})})};c.create=h;c.createAbortError=p;c.createAbortController=v;c.throwIfAborted=D;c.isAborted=E;c.throwIfAbortError=function(a){if(q(a))throw a;};c.throwIfNotAbortError=function(a){if(!q(a))throw a;};c.onAbort=x;c.onAbortOrThrow=
function(a,b){a=w(a);if(!k.isNone(a))return D(a),B.once(a,"abort",function(){return b(p())})};c.isAbortError=q;c.ignoreAbortErrors=function(a){return a.catch(function(a){if(!q(a))throw a;})};c.logOnError=function(a,b){return a.catch(function(a){q(a)||(b=k.isSome(b)?b:K,b.error(a))})};c.createDeferred=y;c.eachAlways=z;c.isThenable=function(a){return a&&"function"===typeof a.then};c.eachAlwaysValues=function(a){return z(a).then(function(a){return a.filter(function(a){return!!a.value}).map(function(a){return a.value})})};
c.first=function(a){return a&&a.length?h(function(b,d){for(var c=0;c<a.length;c++)a[c].then(b,d)}):l()};c.reject=function(a){if(r("esri-native-promise"))return Promise.reject(a);var b=new u;b.reject(a);return b.promise};c.resolve=l;c.after=F;c.timeout=function(a,b,d,c){var e=d&&"abort"in d?d:null;null!=c||e||(c=d);var f=setTimeout(function(){f=0;e&&e.abort()},b),g=function(){throw c||new A("promiseUtils:timeout","The wrapped promise did not resolve within "+b+" ms");};return a.then(function(a){if(0===
f)throw g();clearTimeout(f);return a},function(a){clearTimeout(f);throw 0===f?g():a;})};c.wrapCallback=function(a){var b=!1;return h(function(){a(function(a){b||l(a)})},function(){return b=!0})};c.isPromiseLike=function(a){return a&&"function"===typeof a.then};c.when=t;c.debounce=function(a,b){void 0===b&&(b=-1);var c,e,n,f,g=null,h=function(){for(var d=[],m=0;m<arguments.length;m++)d[m]=arguments[m];if(c)return e=d,f&&f.reject(p()),f=y(),d=f.promise,g&&(m=g,g=null,m.abort()),d;n=f||y();f=null;if(0<
b){var k=v(),q=c=t(a.apply(void 0,d.concat([k.signal])));F(b).then(function(){c===q&&(f?k.abort():g=k)})}else c=1,c=t(a.apply(void 0,d));var d=function(){var a=e;e=n=c=g=null;null!=a&&h.apply(void 0,a)},m=c,l=n;m.then(d,d);m.then(l.resolve,l.reject);return l.promise};return h};c.createResolver=function(a){var b,c;a=h(function(a,d){b=a;c=d},a);var e=function(a){b(a)};e.resolve=function(a){return b(a)};e.reject=function(a){return c(a)};e.timeout=function(a,b){return I.default.setTimeout(function(){return e.reject(b)},
a)};e.promise=a;return e};c.always=function(a,b){return a.then(b,b)}});