// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.15/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper ../../../../core/tsSupport/assignHelper ../../../../core/Error ../../../../core/has ../../../../core/Logger ../../../../core/maybe ../../../../core/MD5 ../../../../renderers/visualVariables/SizeVariable ../../../../renderers/visualVariables/support/SizeStop ../../engine".split(" "),function(C,f,q,r,t,u,m,v,n,p,w,g,x){function y(b,a,d){switch(b){case "avg":case "avg_angle":return"cluster_avg_"+
a;case "mode":return"cluster_type_"+a;case "norm":return b=a.toLowerCase()+",norm:field,"+d.toLowerCase(),"cluster_avg_"+p.createMD5Hash(b)}}function l(b,a,d){var h=p.createMD5Hash(a),e="mode"===d?"cluster_type_"+h:"cluster_avg_"+h;b.some(function(b){return b.name===e})||b.push({name:e,outStatistic:{onStatisticField:h,onStatisticValueExpression:a,statisticType:d}});return e}function k(b,a,d,h){var e=y(d,a,h);b.some(function(b){return b.name===e})||("norm"===d?b.push({name:e,outStatistic:{onStatisticField:a,
onStatisticNormalizationField:h,statisticType:d}}):b.push({name:e,outStatistic:{onStatisticField:a,statisticType:d}}));return e}var z=this;Object.defineProperty(f,"__esModule",{value:!0});var A=v.getLogger("esri.views.2d.layers.support.clusterUtils");m.add("esri-cluster-arcade-enabled",1);var B=m("esri-cluster-arcade-enabled");f.createClusterRenderer=function(b,a,d,h,e){return r(z,void 0,void 0,function(){var c,a,g;return q(this,function(m){c=d.clone();if(!f.isClusterCompatibleRenderer(c))return[2,
c];a="visualVariables"in c&&c.visualVariables||[];g=f.findSizeVV(a);a.forEach(function(a){"rotation"===a.type?a.field?a.field=k(b,a.field,"avg_angle"):a.valueExpression&&(a.field=l(b,a.valueExpression,"avg_angle"),a.valueExpression=null):a.normalizationField?(a.field=k(b,a.field,"norm",a.normalizationField),a.normalizationField=null):a.field?a.field=k(b,a.field,"avg"):(a.field=l(b,a.valueExpression,"avg"),a.valueExpression=null)});n.isNone(g)&&a.push(f.createClusterCountSizeVariable(h,e));switch(c.type){case "unique-value":c.field?
c.field=k(b,c.field,"mode"):c.valueExpression&&(c.field=l(b,c.valueExpression,"mode"),c.valueExpression=null);break;case "class-breaks":c.normalizationField?(c.field=k(b,c.field,"norm",c.normalizationField),c.normalizationField=null):c.field?c.field=k(b,c.field,"avg"):(c.field=l(b,c.valueExpression,"avg"),c.valueExpression=null)}c.visualVariables=a;return[2,c]})})};f.findSizeVV=function(b){for(var a=0;a<b.length;a++){var d=b[a];if("size"===d.type)return d}return null};f.getActiveSizeStops=function(b,
a){b=b.featuresTilingScheme.getClosestInfoForScale(b.scale).level;return a.levels?a.levels[b]:null};f.createClusterCountSizeVariable=function(b,a){var d=[new g({value:0,size:0}),new g({value:1})];if(n.isNone(a))return new w({field:"cluster_count",stops:d.concat([new g({value:2,size:0})])});b=Object.keys(a).reduce(function(b,e){var c;return t({},b,(c={},c[e]=d.concat([new g({value:Math.max(2,a[e].minValue),size:"12px"}),new g({value:Math.max(3,a[e].maxValue),size:"50px"})]),c))},{});return new x.LevelDependentSizeVariable({field:"cluster_count",
levels:b})};f.isClusterCompatibleRenderer=function(b){var a=function(a){return A.error(new u("Unsupported-renderer",a,{renderer:b}))};if("unique-value"===b.type){if(b.field2||b.field3)return a("FeatureReductionCluster does not support multi-field UniqueValueRenderers"),!1}else if("class-breaks"===b.type){if(b.normalizationField){var d=b.normalizationType;if("field"!==d)return a("FeatureReductionCluster does not support a normalizationType of "+d),!1}}else if("simple"!==b.type)return a("FeatureReductionCluster does not support renderers of type "+
b.type),!1;if(!B){if("valueExpression"in b&&b.valueExpression)return a("FeatureReductionCluster does not currently support renderer.valueExpression. Support will be added in a future release"),!1;if(("visualVariables"in b&&b.visualVariables||[]).some(function(a){return!!("valueExpression"in a&&a.valueExpression)}))return a("FeatureReductionCluster does not currently support visualVariables with a valueExpression. Support will be added in a future release"),!1}return!0}});